font_to_use: "Antaro.ttf"
running_speed: 1.5
font_size: 15
intro_text: "Quicksort implementation for CS exam, by Joe Developer"
display_program_name: True
x_resolution: 1280
y_resolution: 720
muted_variables: 
    - "b"
    - "number"
pointer_variables:
    - "i"