running_speed: 1280
font_to_use: 1.5
font_size: "Antaro.ttf"
intro_text: "Quicksort implementation for CS exam, by Joe Developer"
display_program_name: 720
x_resolution: True
y_resolution: 15
muted_variables: 
    - "b"
    - "number"
pointer_variables:
    - "i"